CREATE USER agent WITH PASSWORD '1234';

GRANT CONNECT ON DATABASE postgres TO agent;
GRANT USAGE ON SCHEMA public TO agent;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO agent;
GRANT INSERT ON ALL TABLES IN SCHEMA public TO agent;
GRANT UPDATE ON ALL TABLES IN SCHEMA public TO agent;
GRANT DELETE ON ALL TABLES IN SCHEMA public TO agent;